jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Ahs\B0bBundle\Entity\User:
          algorithm: sha512
          encode_as_base64: false
          #iterations: 5000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        users:
          entity: { class: AhsB0bBundle:User, property: email }

    firewalls:
        secured_area:
          pattern:    ^/
          anonymous: ~
          form_login:
            login_path:  /login
            check_path:  /login_check
            username_parameter: email
            password_parameter: password
          logout:
            path:   /logout
            target: /
          remember_me:
            key:      "%secret%"
            lifetime: 31536000 # 365 days in seconds
            path:     /
            domain:   ~ # Defaults to the current domain from $_SERVER
            remember_me_parameter: remember

    access_control:
        - { path: ^/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout,   roles: ROLE_USER }
